<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mws.Domain/Mws.Domain.csproj" />
    <ProjectReference Include="../../src/Mws.Persistence.Json/Mws.Persistence.Json.csproj" />
    <ProjectReference Include="../../src/Mws.Simulation.Runtime/Mws.Simulation.Runtime.csproj" />
  </ItemGroup>
</Project>
